apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld-admin.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "palworld-admin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "palworld-admin.name" . }}
  template:
    metadata:
      labels:
        {{- include "palworld-admin.labels" . | nindent 8 }}
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ include "palworld-admin.name" . }}
      {{- end }}
      containers:
        - name: {{ include "palworld-admin.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PALWORLD_NAMESPACE
              value: {{ .Values.palworldNamespace | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
